name: Build & Release AkiStudio

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew :app:assembleRelease --stacktrace

      - name: Decode keystore
        if: github.ref == 'refs/heads/main'
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks

      - name: Sign APK
        if: github.ref == 'refs/heads/main'
        run: |
          APK=$(find app/build/outputs/apk/release -name "*.apk" | head -n 1)
          cp "$APK" unsigned.apk
          $ANDROID_HOME/build-tools/*/apksigner sign \
            --ks keystore.jks \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEY_PASS }}" \
            --key-pass pass:"${{ secrets.KEY_PASS }}" \
            --out signed.apk \
            unsigned.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AkiStudio-signed-apk
          path: signed.apk

      - name: Create GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: AkiStudio v${{ github.run_number }}
          draft: false
          prerelease: true
          files: signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs_site
          enable_jekyll: false
          
